target-version = "py312"
line-length = 100

[lint]
select = [
  "E",
  "F",
  "I",
  "UP",
  "D",
  "ANN",
  "B",
  "C4",
  "NPY",
  "PD",
  "PIE",
  "PL",
  "Q",
  "RUF",
  "SIM",
]
ignore = ["ANN101", "ANN102", "D104"]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"tests/**/*.py" = ["D100", "D101", "D102", "D103", "D104", "D105", "ANN401"]
"docs/**/*.py" = ["D100", "D101", "D102", "D103", "D104", "D105"]
