[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = [
  "E",
  "F",
  "I",
  "UP",
  "D",
  "ANN",
  "B",
  "C4",
  "NPY",
  "PD",
  "PIE",
  "PL",
  "Q",
  "RUF",
  "SIM",
]
ignore = [
  "ANN101",
  "ANN102",
  "D104",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D100", "D101", "D102", "D103", "D104", "D105", "ANN401"]
"docs/**/*.py" = ["D100", "D101", "D102", "D103", "D104", "D105"]

